import { oracleDb } from './src/infrastructure/database/oracle-connection';

async function main() {
  console.log('Automating table creation...');

  const statements = [
    `CREATE TABLE "Roles" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "name" VARCHAR2(255) NOT NULL UNIQUE,
        "description" VARCHAR2(255),
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE "Users" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "username" VARCHAR2(255) NOT NULL UNIQUE,
        "name" VARCHAR2(255) NOT NULL,
        "lastName" VARCHAR2(255) NOT NULL,
        "cedula" VARCHAR2(20) UNIQUE,
        "email" VARCHAR2(255) NOT NULL UNIQUE,
        "password" VARCHAR2(255) NOT NULL,
        "roleId" VARCHAR2(36) NOT NULL,
        "isActive" NUMBER(1) DEFAULT 1 NOT NULL,
        "loginAttempts" NUMBER(10) DEFAULT 0 NOT NULL,
        "isLocked" NUMBER(1) DEFAULT 0 NOT NULL,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_users_role FOREIGN KEY ("roleId") REFERENCES "Roles"("id")
    )`,
    `CREATE TABLE "Customers" (
        "id" VARCHAR2(50) PRIMARY KEY,
        "name" VARCHAR2(255) NOT NULL,
        "lastName" VARCHAR2(255) NOT NULL,
        "phone" VARCHAR2(50) NOT NULL,
        "address" VARCHAR2(500) NOT NULL,
        "email" VARCHAR2(255) NOT NULL UNIQUE,
        "isActive" NUMBER(1) DEFAULT 1 NOT NULL,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE "Products" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "code" VARCHAR2(100) NOT NULL UNIQUE,
        "name" VARCHAR2(255) NOT NULL,
        "price" NUMBER(10, 2) NOT NULL,
        "stock" NUMBER(10) NOT NULL,
        "appliesIva" NUMBER(1) DEFAULT 1 NOT NULL,
        "isActive" NUMBER(1) DEFAULT 1 NOT NULL,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE "PaymentMethods" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "name" VARCHAR2(255) NOT NULL UNIQUE,
        "isActive" NUMBER(1) DEFAULT 1 NOT NULL,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE "Sales" (
        "id" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "number" VARCHAR2(50) NOT NULL UNIQUE,
        "date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "status" VARCHAR2(50) DEFAULT 'Draft' NOT NULL,
        "customerId" VARCHAR2(50) NOT NULL,
        "userId" VARCHAR2(36) NOT NULL,
        "paymentMethodId" VARCHAR2(36) NOT NULL,
        "subtotal" NUMBER(10, 2) NOT NULL,
        "iva" NUMBER(10, 2) NOT NULL,
        "total" NUMBER(10, 2) NOT NULL,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_sales_customer FOREIGN KEY ("customerId") REFERENCES "Customers"("id"),
        CONSTRAINT fk_sales_user FOREIGN KEY ("userId") REFERENCES "Users"("id"),
        CONSTRAINT fk_sales_payment FOREIGN KEY ("paymentMethodId") REFERENCES "PaymentMethods"("id")
    )`,
    `CREATE TABLE "SaleDetails" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "saleId" NUMBER(10) NOT NULL,
        "productId" VARCHAR2(36) NOT NULL,
        "productName" VARCHAR2(255) NOT NULL,
        "productCode" VARCHAR2(100) NOT NULL,
        "quantity" NUMBER(10) NOT NULL,
        "price" NUMBER(10, 2) NOT NULL,
        "subtotal" NUMBER(10, 2) NOT NULL,
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_details_sale FOREIGN KEY ("saleId") REFERENCES "Sales"("id") ON DELETE CASCADE,
        CONSTRAINT fk_details_product FOREIGN KEY ("productId") REFERENCES "Products"("id")
    )`,
    `CREATE TABLE "StockMovements" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "productId" VARCHAR2(36) NOT NULL,
        "type" VARCHAR2(50) NOT NULL,
        "quantity" NUMBER(10) NOT NULL,
        "stockBefore" NUMBER(10) NOT NULL,
        "stockAfter" NUMBER(10) NOT NULL,
        "userId" VARCHAR2(36) NOT NULL,
        "reference" VARCHAR2(255),
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_movements_product FOREIGN KEY ("productId") REFERENCES "Products"("id"),
        CONSTRAINT fk_movements_user FOREIGN KEY ("userId") REFERENCES "Users"("id")
    )`,
    `CREATE TABLE "ErrorLogs" (
        "id" VARCHAR2(36) PRIMARY KEY,
        "message" CLOB NOT NULL,
        "exceptionType" VARCHAR2(255),
        "stackTrace" CLOB,
        "source" VARCHAR2(500),
        "userId" VARCHAR2(36),
        "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_errors_user FOREIGN KEY ("userId") REFERENCES "Users"("id")
    )`,
    `CREATE INDEX idx_users_username ON "Users"("username")`,
    `CREATE INDEX idx_users_email ON "Users"("email")`,
    `CREATE INDEX idx_customers_name ON "Customers"("name")`,
    `CREATE INDEX idx_customers_lastName ON "Customers"("lastName")`,
    `CREATE INDEX idx_products_name ON "Products"("name")`,
    `CREATE INDEX idx_products_code ON "Products"("code")`,
    `CREATE INDEX idx_sales_number ON "Sales"("number")`,
    `CREATE INDEX idx_sales_date ON "Sales"("date")`,
    `CREATE INDEX idx_errorlogs_date ON "ErrorLogs"("createdAt")`
  ];

  for (const stmt of statements) {
    try {
      await oracleDb.raw(stmt);
      console.log('Executed:', stmt.split('(')[0].trim());
    } catch (e: any) {
      if (e.message.includes('ORA-00955')) {
        console.log('Table or index already exists, skipping...');
      } else {
        console.error('Error executing:', stmt, e.message);
      }
    }
  }

  console.log('All tables created successfully!');
  await oracleDb.destroy();
}

main();
