import { oracleDb } from './src/infrastructure/database/oracle-connection';

async function main() {
  console.log('Fixing Sales sequence...');
  try {
    // Determine the max ID from Sales
    const result = await oracleDb.raw('SELECT MAX("id") as max_id FROM "Sales"');
    const maxId = result[0].MAX_ID || result[0].max_id;
    const nextId = maxId + 1;
    
    console.log(`Max Sale ID is ${maxId}. Restarting identity sequence at ${nextId}...`);
    
    // Alter the sequence
    await oracleDb.raw(`ALTER TABLE "Sales" MODIFY "id" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE)`);
    
    console.log('Identity sequence successfully updated!');
  } catch (error: any) {
    console.error('Failed to fix sequence:', error.message);
  } finally {
    await oracleDb.destroy();
  }
}
main();
